server:
  port: 8020
spring:
  application:
    name: cloud-scheduler-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.110:3306/dm_scheduler?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Jxiuye@163.com
mybatis:
  mapper-locations: classpath:mapper/*.xml